name: onvif
description: A fluttering package for finding and displaying CCTV cameras on local networks.
version: 0.0.3
author: Mostafa Dadkhah <Mostafa.time@gmail.com>
homepage: https://github.com/MostafaDadkhah/Flutter_onvif

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  uuid: ^2.0.4
  rxdart: ^0.24.0
  xml: ^4.5.0
  dio: ^3.0.9
  collection: ^1.14.11
  nonce: ^0.1.0
  crypto: ^2.1.3

dev_dependencies:
  test: ^1.15.7
